apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql-2
  name: mysql-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-2
  template:
    metadata:
      labels:
        app: mysql-2
    spec:
      containers:
        - image: mysql:8.3.0
          name: mysql-2
#          args:
#            - "--ignore-db-dir"
#            - "lost+found"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mysql_root_password
                  name: mysql-2-secrets
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-2-data
#              subPath: mysql
            - mountPath: /docker-entrypoint-initdb.d
              name: mysql-2-initdb-config
      volumes:
        - name: mysql-2-data
          persistentVolumeClaim:
            claimName: mysql-2-pvc
        - name: mysql-2-initdb-config
          configMap:
            name: mysql-2-init-db-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-2
  name: mysql-2
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql-2
---
apiVersion: v1
data:
  mysql_root_password: cm9vdA==
kind: Secret
metadata:
  name: mysql-2-secrets
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-2-pv
spec:
  storageClassName: 'standard'
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/mysql-2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-2-pvc
spec:
  storageClassName: 'standard'
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-2-init-db-config
data:
  initdb.sql: |
    create database if not exists order_service;