spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:mysql://localhost:3307/inventory_service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8082

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus

  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: inventory-service

  tracing:
    sampling:
      probability: 1.0